# Exercices de synthèse
## Génération de données et agrégation de matrices

Nous souhaitons créer une matrice 10x3 dont la première colonne contient les indices 1 à 10 dans l'ordre. La seconde colonne contiendra des nombres aléatoires entre 0 et 1. La troisième colonne ne contiendra que des 0.
Vous ajouterez ensuite une ligne en haut de la matrice contenant les indices de colonne 1 à 3.

**NB:** vous pouvez créer des matrices dans des matrices, c'est-à-dire faire appel à des fonctions dans les []. 

**NB2:** à la fin du processus, on veut un ```np.array```, il faut soit travailler en numpy tout le temps, soit penser à convertir les listes python.

Exemple de résultat possible:

    1.00000    2.00000    3.00000
    1.00000    0.03479    0.00000
    2.00000    0.66074    0.00000
    3.00000    0.15187    0.00000
    4.00000    0.03640    0.00000
    5.00000    0.62497    0.00000
    6.00000    0.54774    0.00000
    7.00000    0.68919    0.00000
    8.00000    0.86146    0.00000
    9.00000    0.72030    0.00000
    10.0000    0.84590    0.00000


In [11]:
import numpy as np

a = np.zeros((11, 3))
a[0] = range(1, 4)
a[1:, 0] = range(1, 11)
a[1:, 1] = np.random.random((10,))
a

array([[ 1.        ,  2.        ,  3.        ],
       [ 1.        ,  0.74977732,  0.        ],
       [ 2.        ,  0.62279464,  0.        ],
       [ 3.        ,  0.59761689,  0.        ],
       [ 4.        ,  0.51224065,  0.        ],
       [ 5.        ,  0.09503464,  0.        ],
       [ 6.        ,  0.74186244,  0.        ],
       [ 7.        ,  0.05818061,  0.        ],
       [ 8.        ,  0.50437102,  0.        ],
       [ 9.        ,  0.13799422,  0.        ],
       [10.        ,  0.39917502,  0.        ]])

## Calcul de moyennes, écarts-types (à la main *vs* fonction numpy)

Soit la matrice de donnée suivante:
```
M = np.array([[8, 3, 7, 3, 2, 7, 9, 1, 2, 9],
              [2, 1, 3, 7, 4, 2, 5, 4, 6, 0],
              [5, 1, 4, 1, 1, 1, 0, 6, 5, 0]])
```

Construire la fonction ```stats``` qui prend en argument une matrice et retourne le vecteur contenant les moyennes des colonnes et un second vecteur contenant les écarts-types des colonnes.

**Note:** vous ferez les calculs à la main, avec des boucles et vous comparerez les résultats avec les fonctions ```np.mean``` et ```np.std```.

**Note 2:** une fonction définie par ```def mafonction(arg):``` peut retourner un tuple, c'est à dire plusieurs résultats agrégés dans une structure simple ```return vec1, vec2```. L'appel (le plus simple) à ma fonction sera de la forme: ```res1, res2 = mafonction(arg)```

In [14]:
M = np.array([[8, 3, 7, 3, 2, 7, 9, 1, 2, 9],
              [2, 1, 3, 7, 4, 2, 5, 4, 6, 0],
              [5, 1, 4, 1, 1, 1, 0, 6, 5, 0]])

def stats(M):
    l, c = M.shape
    means = []
    stds = []
    for j in range(c):
        mean = sum(M[:, j])/l
        std = ((sum(list(map(lambda x: x**2, M[:, j])))/l) - mean**2) ** .5
        means.append(mean)
        stds.append(std)
    return means, stds

print(stats(M))  
print(np.mean(M, axis=0), np.std(M, axis=0))


([5.0, 1.6666666666666667, 4.666666666666667, 3.6666666666666665, 2.3333333333333335, 3.3333333333333335, 4.666666666666667, 3.6666666666666665, 4.333333333333333, 3.0], [2.449489742783178, 0.9428090415820631, 1.699673171197594, 2.494438257849295, 1.2472191289246466, 2.6246692913372702, 3.6817870057290865, 2.054804667656326, 1.699673171197596, 4.242640687119285])
[5.         1.66666667 4.66666667 3.66666667 2.33333333 3.33333333
 4.66666667 3.66666667 4.33333333 3.        ] [2.44948974 0.94280904 1.69967317 2.49443826 1.24721913 2.62466929
 3.68178701 2.05480467 1.69967317 4.24264069]


## Table de contingence en numpy

Construction d'une liste de notes d'étudiants (50 notes entre 0 et 20): l'exercice est le même que celui proposé dans la partie python, mais **à réaliser entièrement dans l'environnement numpy**.

* Génération d'un vecteur de notes tirées aléatoirement à l'aide de la fonction: ```np.random.randint``` 
* Création d'une nouvelle liste comptant combien de note de chaque niveau apparaissent dans la liste (table de contingence)
* Création d'une troisième liste contenant toutes les notes supérieures à 10
    
Affichage des deux listes et vérification

Exercice sur la gestion des listes et des boucles.

In [17]:
notes = np.random.randint(0, 21, 50)
uniques, counts = np.unique(notes, return_counts=True)
filters = notes[notes > 10]
print(notes)
print(counts)
print(filters)

[ 6 18 17 20  8 15  7 10  7  2 15 13  3  7  9 12 16  1 11 15 14  8  1  9
 11 20 11 14  0 10 20 17  7 20  9 20 17  4 17  4  0  7  6  8 17 17  1  5
  3 12]
[2 3 1 2 2 1 2 5 3 3 2 3 2 1 2 3 1 6 1 5]
[18 17 20 15 15 13 12 16 11 15 14 11 20 11 14 20 17 20 20 17 17 17 17 12]


## Premier contact avec la documentation

Vous allez générer la matrice suivante:
```
[[0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]]
```
Cette génération peut se faire en une ligne à condition d'utiliser la fonction ```np.tile``` dont la documentation se trouve : 
https://numpy.org/doc/stable/reference/generated/numpy.tile.html

Au-delà de la question formelle, l'enjeu est d'apprendre à se servir de la documentation de numpy.

In [18]:
np.tile([0, 1, 2], [10, 2])

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

# Manipulation standard de matrices

1. Générer une matrice ```10x3``` de valeurs distribuées selon une loi normale centrée réduite (```np.random.randn```)
1. Faites en sorte que l'écart-type des données passe à 4 et vérifier que c'est le approximativement cas avec la fonction ```np.std```
1. Centrer la première colonne sur 10, la seconde sur 12 et la troisième sur 14. Vérifier que les moyennes sont bonnes avec ```np.mean(axis=0)``` <BR> **NB:** il est impératif de travailler sur la dispersion avant le centrage (vérifiez cette affirmation en inversant les deux réponses si vous avez un doute)
1. Seuiller toutes les valeurs inférieures à 5 avec ```np.maximum```
1. Seuiller toutes les valeurs supérieures à 18
1. Compter combien de valeurs se situent entre 8 et 12 (exclus)

In [23]:
a = 4 * np.random.randn(10, 3)
print(a)
print(np.std(a))

[[ -4.01627437   3.99053265   7.33501463]
 [  3.94774175   0.54022013   2.01883551]
 [  0.74518981   4.14333304  -2.26545277]
 [  6.22441778   2.62109218   5.89799736]
 [ -2.41355898 -12.29559385   1.67973433]
 [ -2.83521386  -1.25333553  -4.31123388]
 [  8.15322638  -0.57466701  -7.12112604]
 [ -2.2928109   -0.83155598  -1.78441833]
 [ -5.92360474   4.43462511   7.69831315]
 [  0.92533565  -3.66955169  -2.54576092]]
4.6806997213345145


# Travail en plus grande dimension

numpy ne vous limite pas à 2 dimensions...
1. Créer un cube ```C``` de dimension ```4x3x2``` (avec la fonction ```np.zeros``` par exemple). Dans la suite on choisira de voire cette structure de données comme 4 matrices ```3x2```. Vérifier que vous pouvez acceder à la matrice ```i``` par la commande ```C[i]```.
1. Remplir ce cube avec 15 valeurs aléatoires tirées entre 0 et 10 et positionnées dans des cases aléatoires
1. Diviser le cube par des facteurs de normalisation de sorte à ce que chaque matrice ```3x2``` ait une somme de ```1```. Afficher les matrices pour vérifier *à l'oeil* que les sommes sont bonnes.
1. Remplacer la sous-matrice ```2``` par une matrice remplie de 1.



In [26]:
C = np.zeros((4,3,2))
n = 15
index = np.zeros((n, 3))
index[:, 0] = np.random.randint(0, 4, n)
index[:, 1] = np.random.randint(0, 3, n)
index[:, 2] = np.random.randint(0, 2, n)
C[index]

IndexError: arrays used as indices must be of integer (or boolean) type

### Traduction de matrice
* Générer une matrice aléatoire `m` de taille (15,2) contenant des indices aléatoires entre 0 et 3.
* Construire le dictionnaire `dico` {1:'titi', 2:'toto', ...}
* La méthode `get` du dictionnaire permet de traduire une valeur de `m`
* Utiliser la commande `np.vectorize` pour traduire en une ligne et sans boucle toute la matrice `m` en une matrice `mtxt`